# Generated by Django 6.0.6 on 2026-07-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publicaciones", "0002_publicacion_idioma"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicacion",
            name="url_video",
            field=models.URLField(
                blank=True,
                help_text="Enlace del audiolibro o video de YouTube",
                null=True,
            ),
        ),
    ]
